package com.certchain.artifact;

import jakarta.annotation.PreDestroy;
import java.io.IOException;
import java.net.URI;
import java.time.Duration;
import java.util.regex.Pattern;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.HeadObjectRequest;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.services.s3.model.S3Exception;

/** Private S3-compatible object storage. Keys are generated by the backend, never by clients. */
@Component
@ConditionalOnProperty(prefix = "app.storage", name = "type", havingValue = "s3")
public class S3ArtifactStorage implements ArtifactStorage {
    private static final Pattern KEY = Pattern.compile(
        "certificates/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/certificate\\.pdf");
    private static final int MAX_BYTES = 10 * 1024 * 1024;
    private final S3Client client;
    private final String bucket;

    public S3ArtifactStorage(
        @Value("${app.storage.s3.endpoint}") String endpoint,
        @Value("${app.storage.s3.region}") String region,
        @Value("${app.storage.s3.bucket}") String bucket,
        @Value("${app.storage.s3.access-key-id}") String accessKeyId,
        @Value("${app.storage.s3.secret-access-key}") String secretAccessKey
    ) {
        if (endpoint.isBlank() || region.isBlank() || bucket.isBlank()
            || accessKeyId.isBlank() || secretAccessKey.isBlank()) {
            throw new IllegalArgumentException("S3 artifact storage requires endpoint, region, bucket and credentials");
        }
        URI uri = URI.create(endpoint);
        if (!"https".equalsIgnoreCase(uri.getScheme()) || uri.getHost() == null
            || uri.getUserInfo() != null || uri.getQuery() != null || uri.getFragment() != null
            || (uri.getRawPath() != null && !uri.getRawPath().isEmpty() && !"/".equals(uri.getRawPath()))) {
            throw new IllegalArgumentException("S3 artifact endpoint must be an HTTPS origin");
        }
        this.bucket = bucket;
        this.client = S3Client.builder()
            .endpointOverride(uri)
            .region(Region.of(region))
            .overrideConfiguration(config -> config
                .apiCallAttemptTimeout(Duration.ofSeconds(10))
                .apiCallTimeout(Duration.ofSeconds(20)))
            .credentialsProvider(StaticCredentialsProvider.create(
                AwsBasicCredentials.create(accessKeyId, secretAccessKey)))
            .forcePathStyle(true)
            .build();
    }

    // Package-private for a small adapter test without a live storage account.
    S3ArtifactStorage(S3Client client, String bucket) {
        this.client = client;
        this.bucket = bucket;
    }

    private static String checkedKey(String key) {
        if (key == null || !KEY.matcher(key).matches()) throw new IllegalArgumentException("Invalid artifact key");
        return key;
    }

    @Override
    public void write(String key, byte[] content) {
        checkedKey(key);
        if (content == null || content.length == 0 || content.length > MAX_BYTES)
            throw new IllegalArgumentException("Invalid artifact size");
        client.putObject(PutObjectRequest.builder().bucket(bucket).key(key)
            .contentType("application/pdf").build(), RequestBody.fromBytes(content));
    }

    @Override
    public byte[] read(String key) {
        checkedKey(key);
        try {
            var metadata = client.headObject(HeadObjectRequest.builder().bucket(bucket).key(key).build());
            if (metadata.contentLength() == null || metadata.contentLength() > MAX_BYTES)
                throw new IllegalStateException("Artifact is unavailable");
            try (var stream = client.getObject(GetObjectRequest.builder().bucket(bucket).key(key).build())) {
                byte[] content = stream.readNBytes(MAX_BYTES + 1);
                if (content.length > MAX_BYTES) throw new IllegalStateException("Artifact is unavailable");
                return content;
            }
        } catch (IOException | S3Exception error) {
            throw new IllegalStateException("Artifact read failed", error);
        }
    }

    @Override
    public boolean exists(String key) {
        checkedKey(key);
        try {
            client.headObject(HeadObjectRequest.builder().bucket(bucket).key(key).build());
            return true;
        } catch (S3Exception error) {
            if (error.statusCode() == 404) return false;
            throw error;
        }
    }

    @PreDestroy
    public void close() { client.close(); }
}
